seed: 1337
batch_size: 4
lr: 1.0e-5
max_steps: 10
beta: 0.1

data:
  path: wakea/data/schemas/pref_pairs.jsonl
  tokenizer: null
  max_len: 256

model_cfg: wakea/configs/model.yaml
output_dir: checkouts/dpo
